apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: appinsightsconfig
  namespace: agileball
spec:
  tracing:
    samplingRate: "1"
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: native
  namespace: agileball
spec:
  type: exporters.native
  version: v1
  metadata:
  - name: enabled
    value: "true"
  - name: agentEndpoint
    value: "otel-collector.default.svc.cluster.local:55678"
