apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: appconfig
  namespace: agileball
spec:
  # mtls:
  #   enabled: true
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://zipkin.default.svc.cluster.local:9411/api/v2/spans"
      #endpointAddress: "http://otel-collector.default.svc.cluster.local:9411/api/v2/spans"

    