apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: agileball-runner
  name: agileball-runner
  namespace: agileball
  # annotations:
  #   linkerd.io/inject: enabled
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agileball-runner
  template:
    metadata:
      labels:
        app: agileball-runner
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: agileball-runner
        dapr.io/app-port: "80"
        dapr.io/config: "appconfig"
    spec:
      containers:
      - image: agilewaysreg.azurecr.io/agileball/runner:1.1
        name: runner
        resources: {}
