apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: agileball
spec:
  type: pubsub.redis
  metadata:
  - name: redisHost
    value: redis-master.default.svc.cluster.local:6379
  - name: redisPassword
    value: YBR8ipvWxA
    # secretKeyRef:
    #   name: redis
    #   key: redis-password